routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('/');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('roles','RoleController')->except('show');
Route::get('posts/getList', 'PostController@getList')->name('posts.getList');
Route::resource('posts', 'PostController');

Route::get('/profil/{id}', 'ProfilController@show')->name('profil.show');
Route::delete('/profil', 'ProfilController@deleteUser')->name('profil.deleteUser');
Route::post('/profil', 'ProfilController@updateUserRole')->name('profil.updateUserRole');
Route::post('/profil/update-data', 'ProfilController@updateUserData')->name('profil.updateUserData');

Route::get('/paiement/{post}', 'PaiementController@formulaire')->name('payment.form');
Route::get('/paiement-ok/{post}', 'PaiementController@paiementOK')->name('payment.ok');

app/Models/Post.php
<?php

namespace App\Models;

use App\Models\User;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'title',
        'description',
        'image',
        'price',
        'category_id',
        'seller_id',
        'buyer_id'
    ];
    
    public function user()
    {
        return $this->belongsTo(User::class, 'seller_id', 'id');
    }

    public function category()
    {
        return $this->belongsTo(PostCategory::class, 'category_id', 'id');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use App\Models\User;
use App\Models\PostCategory;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('layouts.posts.Posts');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function getList()
    {
        $posts = Post::with('user', 'category')->whereNull('buyer_id')->get();

        echo json_encode($posts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categories = PostCategory::all();
        return view('layouts.posts.CreatePost', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Post::Create([
            'title' => $request->get('title'),
            'description' => $request->get('description'),
            'image' => $request->get('image'),
            'price' => $request->get('price'),
            'category_id' => $request->get('category'),
            'seller_id' => Auth::user()->id
        ]);

        return redirect()->route('posts.index');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $post = Post::findOrFail($id);

        return view('layouts.posts.Post', compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::FindOrFail($id);
        $categories = PostCategory::all();
        return view('layouts.posts.EditPost', compact('post', 'categories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $post = Post::findOrFail($id);
        $post->update([
            'title' => $request->get('title'),
            'description' => $request->get('description'),
            'image' => $request->get('image'),
            'price' => $request->get('price'),
            'category_id' => $request->get('category'),
        ]);

        return redirect()->route('posts.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Post::findOrFail($id)->delete();
        return redirect()->route('posts.index');
    }
}

resources/views/layouts/posts/CreatePost.blade.php
@extends('home')

@section('container')
    <div class="card">
        <div class="card-header"><h3>Création d'une annonce</h3></div>
        <div class="card-body">
            <form action="{{ route('posts.store') }}" method="POST">
                @csrf
                <div class="form-group">
                    <label for="title">Titre</label>
                    <input type="text" required class="form-control" id="title" name="title" placeholder="Titre">
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea required class="form-control" id="description" name="description" placeholder="Description"></textarea>
                </div>
                <div class="form-group">
                    <label for="price">Prix</label>
                    <input type="number" required class="form-control" id="price" name="price" placeholder="Prix">
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="text" class="form-control" id="image" name="image" placeholder="Lien de l'image">
                </div>
                <fieldset class="form-group">
                    <div class="row">
                        <legend class="col-form-label col-sm-12 pt-0">Catégorie de l'annonce:</legend>
                        <div class="col-sm-10">
                            @foreach ($categories as $category)
                                @if (Auth::user()->roles->pluck('name')->contains($category->name) || Auth::user()->roles->pluck('name')->contains(env('ADMIN_NAME')))
                                    <div class="form-check">
                                    <input class="form-check-input" type="radio" name="category" id="{{ $category->name }}" value="{{ $category->id }}" checked>
                                        <label class="form-check-label" for="{{ $category->name }}">
                                            {{ $category->name }}
                                        </label>
                                    </div>
                                @endif
                            @endforeach
                        </div>
                    </div>
                </fieldset>
                <button type="submit" class="btn btn-primary">Créer</button>
            </form>
        </div>
    </div>
@endsection

resources/views/layouts/posts/EditPost.blade.php
@extends('home')

@section('container')
    <div class="card">
        <div class="card-header"><h3>Modification de l'annonce</h3></div>
        <div class="card-body">
            <form action="{{ route('posts.update', $post->id) }}" method="POST">
                @method('PUT')
                @csrf
                <div class="form-group">
                    <label for="title">Titre</label>
                <input type="text" required class="form-control" id="title" name="title" placeholder="Titre" value="{{ $post->title }}">
                </div>
                <div class="form-group">
                    <label for="description">Description</label>
                    <textarea required class="form-control" id="description" name="description" placeholder="Description">{{ $post->description }}</textarea>
                </div>
                <div class="form-group">
                    <label for="price">Prix</label>
                    <input type="number" class="form-control" id="price" name="price" value="{{ $post->price }}">
                </div>
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="text" class="form-control" id="image" name="image" placeholder="Lien de l'image" value="{{ $post->image }}">
                </div>
                <fieldset class="form-group">
                    <div class="row">
                        <legend class="col-form-label col-sm-12 pt-0">Catégorie de l'annonce:</legend>
                        <div class="col-sm-10">
                            @foreach ($categories as $category)
                                @if (Auth::user()->roles->pluck('name')->contains($category->name) || Auth::user()->roles->pluck('name')->contains(env('ADMIN_NAME')))
                                    <div class="form-check">
                                    <input class="form-check-input" type="radio" name="category" id="{{ $category->name }}" value="{{ $category->id }}" {{ $post->category_id == $category->id ? 'checked' : '' }}>
                                        <label class="form-check-label" for="{{ $category->name }}">
                                            {{ $category->name }}
                                        </label>
                                    </div>
                                @endif
                            @endforeach
                        </div>
                    </div>
                </fieldset>
                <button type="submit" class="btn btn-primary">Modifier</button>
            </form>
        </div>
    </div>
@endsection

resources/views/layouts/posts/Post.blade.php
@extends('home')

@section('container')
    <div class="container">
        <div class="row justify-content-center">
            <div class="card" style="width: 30rem;">
                @if (filter_var($post->image, FILTER_VALIDATE_URL))
                    <img class="card-img-top" src="{{ $post->image }}" alt="Card image cap">
                @endif
                <div class="card-body">
                    <h5 class="card-title">{{ $post->title }}</h5>
                    <p class="card-text">{{ $post->description }}</p>
                    
                    @if (Auth::check())                           
                        <p>
                            <a id="checkout-button" href="{{ route('payment.form', $post->id) }}" class="btn btn-success">Acheter</a> {{ $post->price }} €
                            @if (Auth::user()->id == $post->seller_id)
                                <form action="{{route('posts.destroy', $post->id)}}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button type="submit" class="btn btn-danger float-right">Supprimer</button>
                                </form>
                                {{-- <a href="#" class="btn btn-danger float-right">Supprimer</a> --}}
                                <a href="{{ route('posts.edit', $post->id) }}" class="btn btn-primary float-right mr-3">Modifier</a>   
                            @endif
                        </p>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/layouts/posts/Posts.blade.php
@extends('home')

@section('container')
    <link rel="stylesheet" type="text/css"
          href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>

    <link rel="stylesheet" type="text/css"
          href="https://cdn.datatables.net/v/bs4/dt-1.10.21/af-2.3.5/b-1.6.2/cr-1.5.2/fc-3.3.1/fh-3.1.7/kt-2.5.2/r-2.2.5/rg-1.1.2/rr-1.2.7/sc-2.0.2/sp-1.1.1/sl-1.3.1/datatables.min.css"/>

    <table class="table table-bordered table-striped table-hover" id="datatable">
        <thead>
        <tr>
            <th>Voir</th>
            <th>Titre</th>
            <th>Description</th>
            <th>Vendeur</th>
            <th>Type</th>
            <th>Prix</th>
            <th>Ajouté le</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
@endSection

@section('script')
    <script
        src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    <script type="text/javascript"
            src="https://cdn.datatables.net/v/bs4/dt-1.10.21/af-2.3.5/b-1.6.2/cr-1.5.2/fc-3.3.1/fh-3.1.7/kt-2.5.2/r-2.2.5/rg-1.1.2/rr-1.2.7/sc-2.0.2/sp-1.1.1/sl-1.3.1/datatables.min.js"></script>

    <script type="text/javascript" src="https://momentjs.com/downloads/moment-with-locales.min.js"></script>

    <script>
        moment.lang("fr");
        let table = $('#datatable').DataTable({
            "ajax": {
                url: './posts/getList',
                type: "GET",
                dataType: 'json',
                dataSrc: ""
            },
            "serverSide": false,
            "searching": true,
            "ordering": true,
            "columns": [
                {"data": null},
                {"data": "title"},
                {"data": "description"},
                {"data": "user.name"},
                {"data": "category.name"},
                {"data": "price"},
                {"data": "created_at"}
            ],
            "columnDefs": [
                {
                    "targets": 0,
                    "orderable": false,
                    "searchable": false,
                    "render": function (data, type, row, meta) {
                        return ('<div class="text-primary edit" data-description="' + row["description"] + '" data-target="' + row["id"] + '"><a href="./posts/' + row["id"] + '"><i class="fa fa-eye fa-lg" ></i></a></div>');
                    }
                },
                {
                    "targets": 5,
                    "orderable": true,
                    "searchable": true,
                    "render": function (data, type, row, meta) {
                        return ('<p>' + row["price"] + ' €</p>');
                    }
                },
                {
                    "targets": 6,
                    "orderable": true,
                    "searchable": true,
                    "render": function (data, type, row, meta) {
                        if (data && data != '') {
                            return moment(data).format('lll');
                        }
                    }
                }
            ],
            pageLength: 25,
            drawCallback: function (settings) {
            },
            success: function () {

            }
        });
    </script>
@endsection