routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
})->name('/');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('roles','RoleController')->except('show');
Route::get('posts/getList', 'PostController@getList')->name('posts.getList');
Route::resource('posts', 'PostController');

Route::get('/profil/{id}', 'ProfilController@show')->name('profil.show');
Route::delete('/profil', 'ProfilController@deleteUser')->name('profil.deleteUser');
Route::post('/profil', 'ProfilController@updateUserRole')->name('profil.updateUserRole');
Route::post('/profil/update-data', 'ProfilController@updateUserData')->name('profil.updateUserData');

Route::get('/paiement/{post}', 'PaiementController@formulaire')->name('payment.form');
Route::get('/paiement-ok/{post}', 'PaiementController@paiementOK')->name('payment.ok');

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
    <div class="d-flex" id="wrapper">

        <!-- Sidebar -->
        <div class="bg-light border-right" id="sidebar-wrapper">
            <div class="list-group list-group-flush">
                <a href="{{ route('posts.index') }}"
                   class="list-group-item list-group-item-action bg-light">Annonces</a>
                @if (Auth::check())
                    <a href="{{ route('posts.create') }}" class="list-group-item list-group-item-action bg-light">Création
                        d'annonce</a>
                @endif
            </div>
        </div>
        <!-- /#sidebar-wrapper -->

        <!-- Page Content -->
        <div id="page-content-wrapper">

            <div class="container-fluid" style="min-width: 80vw">
                @yield('container')
            </div>
        </div>
        <!-- /#page-content-wrapper -->

    </div>
@endsection
@section('script')
    <script
        src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
@endsection